### ISSUE TITLE
MVR checklist

### ISSUE THREAD

**Issue by eigenhombre** [eigenhombre/lll#1]
From https://gist.github.com/eigenhombre/204400c786f9dba3a8d3193d3ce1542a:

See also: http://johnj.com/posts/practices/

- [ ] LICENSE file, including disclaimer
- [ ] Automated build via Docker and GitHub Actions
- [ ] Automated builds include unit tests
- [ ] Automated builds include linting
- [ ] Build badge
- [ ] Artwork
- [ ] Versioned
- [ ] Minimum snippet / example
- [ ] Link to API and/or `help` output
- [ ] Release procedure is automated
- [ ] Project available in public package manager
- [ ] Track outstanding TODOs in Issues
